### ISSUE TITLE
Making the "init.el" file 

### ISSUE THREAD

**Issue by s296ahme** [brittAnderson/Intro2Computing4Psychology#17]
Hi, I'm having some trouble making the `init.el` file in the `.emacs.d` folder in the directory. I managed to make some form of it, but I think the `init.el` I made is a folder because it shows a directory path similar to `.emacs.d`, plus I'm not able to type in it.

Below is what it looks like for me. Can anyone help me make the file? Thanks!
![Problem_making_init_file](https://user-images.githubusercontent.com/70985284/94875970-549f6c80-0424-11eb-8b9f-2763f1443dd6.png)

**Comment by kaitlingaerlan** [comment]
Hi!
All I did to create the file was use the command `C-x C-f` to bring up the "Find file" function in the minibuffer bar at the bottom. When it says "Find file: ~/" you need to type `.emacs.d/init.el` after the backslash so that it can create the file inside the folder and press enter. If you're already in yotur .emacs.d folder then you only need to add the file name.
So I guess you could delete the init.el folder you made and try making the file again. Not sure if you already tried what I described!

**Comment by s296ahme** [comment]
Thank you @kaitlingaerlan, it worked!!

**Comment by brittAnderson** [comment]
This is the power of collaborative coding - more people helping means quicker and better solutions. 
P.S. `C-x C-+` lets you increase the size of the font in an emacs buffer. Can make it easier for older eyes to read the screen shots.
