### ISSUE TITLE
"Your First RMD File" -- Embedded images & Testing

### ISSUE THREAD

**Issue by n96khan** [brittAnderson/Intro2Computing4Psychology#2]
To put an image that will inline on export is it enough to simply use a hyperlink? For example, using the format: 

[image] (image URL)

I also found someone's suggestion on StackOverflow to use: 

foo ![](image.png) bar

Also, how do I check that the code will work? Should I just knit it? I'm asking because I'm not sure if that will change the RScript somehow? 

Any help is appreciated!
-Nusrat

**Comment by brittAnderson** [comment]
There is a good resource for R markdown syntax in the help of RStudio. Look for the "cheatsheet".  Basically it will look something like this:
    
    ![the name people will read](https://...../yourimage.png)

That part in parentheses has to be filled by the url (web address) for you image. Try right clicking on a picture on the internet and copy the link. 

To test in Rstudio you can click the "knit" button and select to html. Check out the video for this unit on Vimeo that shows me typing and doing this for an example. Knitting doesn't change your script. It uses your script to make a new file that ends with .html instead of .Rmd.
