### ISSUE TITLE
Hangman Python elimination problem

### ISSUE THREAD

**Issue by w24cai** [brittAnderson/Intro2Computing4Psychology#20]
1. As mentioned in the hint, it asks to eliminate the letter that were guessed correctly. I am wondering whether we actually mutate the word constant? If so, I am also wondering what indices the function should return? The indices for the modified word or the original word? For example, suppose the word is "apple" and the first guess is "p".  When the next guess is "l", should the function return [3] or [1]? Also, if the user exceeds the max number of time, should the function prints the original word, or the remaining word?

3. Does the first function (the one that returns indices) asks the user to enter the word again? Or do we directly use the word constant in this function?

Thanks in advance!

**Comment by brittAnderson** [comment]
Ah, spoken like a coder. This is what I was referring to when I said the hardest part about coding well is figuring out what you want to do, before you start writing code. Also, ther "right" answer is if your program produces the "right" answer. There are many different routes to that result and they are all correct though some may be more efficient or elegant or idiomatic. For us, at this stage, we just need to get it to work. First get it working, then make it good, fast, elegant, pretty, idiomatic or whatever if you want. 

Remember you know how to copy. Maybe you make a copy of the word and operate on that as letters are eliminated. If so, the indices you need will be different if you always work off the original word. You could also keep a list of correct guesses and use that list to select indices in the list. Then the indices might change as you loop through the list, but you wouldn't care if all you want to do is tell whether any letters are left in the original word un-guessed.

Don't figure out how I wanted you to write the functions. Write the code so that it meets the basic goals set, and if it does that you will be fine. For this course, and coding in general. There is more than one correct solution, you don't have to find mine just one that works. If you can figure out the logic with pen and paper then make those steps "bite-sized" and turn them into functions that you string together. 

Some specifics: 
1. Probably better to display letters than numbers since that is what a human player would understand. Internal to your code use whatever is easier. 
2. For apple, user guesses p, remaining word is ale. User guesses l. Remaining word is ae. If that is what you want you might have a function that says (this is pseduo code just to share an idea): `def ifInWord (word,guess): output = [], for w in word; if guess not equal to w; output.append(w); return(output))` and that output woud become the new word to be input to the function after each guess. 

Will close this issue, but just keeping opening them for each specific question. You can paste code in as well, but format it as such. There is no limit on how many issues you can raise.
