### ISSUE TITLE
Having issues with emacs -- possibly need to uninstall?

### ISSUE THREAD

**Issue by n96khan** [brittAnderson/Intro2Computing4Psychology#23]
I was having trouble working in emacs to download melpa, and as I was working through it I made an error somewhere. Now when I start up emacs it says:
> Warning (initialization): An error occurred while loading ‘/home/khann/.emacs’:
> 
> Symbol's value as variable is void: archives
> 
> To ensure normal operation, you should investigate and remove the
> cause of the error in your initialization file.  Start Emacs with
> the ‘--debug-init’ option to view a complete error backtrace.

So, I ran emacs --debug-init in the terminal and this came up:
> Debugger entered--Lisp error: (void-variable archives)
>   (member archives package)
>   (if (member archives package) package (setq package (append package (list archives))))
>   eval-buffer(#<buffer  *load*> nil "/home/khann/.emacs" nil t)  ; Reading at buffer position 116
>   load-with-code-conversion("/home/khann/.emacs" "/home/khann/.emacs" t t)
>   load("~/.emacs" t t)
>   #f(compiled-function () #<bytecode 0x1e0f4d>)()
>   command-line()
>   normal-top-level()

I'm not sure what to do from here. I googled "how to fix Debugger entered--Lisp error: (void-variable archives)" and someone suggested the only thing to do is uninstall and re-install emacs. Anyone got any better suggestions?
Would be much appreciated!
-Nusrat

**Comment by n96khan** [comment]
I also found someone dealing with a [similar problem](https://stackoverflow.com/questions/45645070/emacs-symbols-value-as-variable-is-void-removes-init-el), but I'm not sure if it's the same exactly.

**Comment by seanrowe95** [comment]
@n96khan have you made any edits to the init.el file?

**Comment by n96khan** [comment]
I created the init.el file, but that's as far as I went with it. I was writing 

> (package-initialize)
> (require 'package)
> (add-to-list 'package archives ' ("melpa" . "http://melpa.org/packages/"))
> (package-init)

I realized I was typing just .emacs (not .emacs.d) and init (not init.el) which is when I deleted a file (to start over) and the problem began.

**Comment by brittAnderson** [comment]
You need to either use ~/.emacs or ~/.emacs.d/init.el  You can't use both. If you have both I suggest deleting the first. You can do this in the terminal with `rm ~/.emacs`, but be very careful with the `rm` command especially as the superuser, because `sudo rm /` will delete your entire Xubuntu system (did that once - not a pleasant day). Then you can see if that fixes your problem. If not, then you have a problem, maybe just a typo, in the init.el file That file is code. .el stands for emacs lisp just like .py stands for python. You can coment *;;" is the comment symbol for emacs lisp everything in that file and see if emacs starts correctly. If so, then add back lines (via uncommenting them)  little by little until you find which lines are giving you the "crash". Then maybe we can diagnose the problem better. 

Two other things you can test is starting emacs from the terminal with `emacs -Q` this will skip reading the init file. If your emacs starts without error you know you have a problem in an initialization file. After that `emacs --debug-init` may give you some more hints.

**Comment by brittAnderson** [comment]
Looking at the fourth line of your code you have `package-init` where above you have `package-initialize`. What the second version supposed to be the same as the first?

**Comment by n96khan** [comment]
I'm not sure what happened, but I 
- used the rm ~/.emacs function
- updated and restarted my computer
- ran the emacs --debug-init command

and the error is no longer showing up. Should I take this as the problem has been dealt with??

**Comment by brittAnderson** [comment]
You started the issue. If the thing that you reported originally is no longer happening then it seems your problem was fixed. If not, just reopen the issue or create a new one with the new error message.
