### ISSUE TITLE
Python Hangman

### ISSUE THREAD

**Issue by kegsss** [brittAnderson/Intro2Computing4Psychology#26]
Hey everyone,

I'm working through a second version of my hangman code for the assessment and have been struggling to wrap my head around what works best for this and how to think about executing it. For those who have found success in writing it, were there any guidelines or examples/tips you have to explain how you got to the correct answer? All help is appreciated!

Thanks ahead of time.

**Comment by bsgunpat** [comment]
Hello,

I also struggled a lot with making this assignment work for me as well. I found this [video](https://www.youtube.com/watch?v=m4nEnsavl6w) really helpful to get some of the more "detailed" steps of the hangman game. You can also find the code from the video [here](https://github.com/kiteco/python-youtube-code/tree/master/build-hangman-in-python).

Hope this helps,
Brittany Gunpat

**Comment by kegsss** [comment]
> Hello,
> 
> I also struggled a lot with making this assignment work for me as well. I found this [video](https://www.youtube.com/watch?v=m4nEnsavl6w) really helpful to get some of the more "detailed" steps of the hangman game. You can also find the code from the video [here](https://github.com/kiteco/python-youtube-code/tree/master/build-hangman-in-python).
> 
> Hope this helps,
> Brittany Gunpat

Thanks Brittany! I'll be sure to check it out.

**Comment by bmmunds** [comment]
What worked for me was to write out what I needed from each step in the game. In theory I knew what hangman was but when writing it in code it took a bit longer to think through. 
My list started with 1) need word 2) how many guesses 3)Ask for letters , etc. 
Then I split out what I want shown to the user and what the computer needs to know to be able to play the game and answer the user. For example, the computer needs to know the word, the number of guess but I don't want the user to see that. 
By having a written map of what I wanted the game to do I was then able to relate it to what we have been taught and know what to google. 
I found the examples online confusing because I wasn't quite able to split out the parts I wanted and relate it to what I have already done in past assignments. 

My assignment was two main for loops. One for loop to cycle through the guess count and the other for loop to cycle through the letters.

**Comment by brittAnderson** [comment]
Thanks for the advice everyone. Open the issue back up if you want, and be as specific as you can. I find that always gets me the most specific and useful feedback.
