### ISSUE TITLE
Your Extended RMD File

### ISSUE THREAD

**Issue by n96khan** [brittAnderson/Intro2Computing4Psychology#3]
Does anyone know how to print only the even numbers from your for loop?

I've found people using an if statement to print out the odd numbers:

if (i %% 2) 

but I haven't found many other methods.

**Comment by seanrowe95** [comment]
Hey @n96khan, that operation (the `%%`) is called the "[Modulo](https://campus.datacamp.com/courses/introduction-to-r-for-finance/the-basics?ex=3)" operator. What it does is return the remainder if you divide the number before the operator by the number after the operator (ex. `4 %% 2` will equate to `0`, `5 %% 2` will equate to `1`). The way it's used in the example that you have, for each i in your loop, it checks `i %% 2`, and if the result of that is `true`, it will execute whatever is in the if statement (i.e printing the number). The tricky part with this example is that they use the fact `0` as a [boolean](https://www.computerhope.com/jargon/b/boolean.htm) is `false` and `1` as a boolean is `true`. A more clear statement of what that condition is doing would be `if (i %% 2 == 1)`. For any odd number, the remainder of being divided by 2 is 1, so only the odd numbers will print. If you want to print the even numbers, every even number divided by 2 will have a remainder of 0, so you can write a similar condition to the one above to just print the even numbers. Hope that helps! If you need any clarification, ask away 👂

**Comment by n96khan** [comment]
@seanrowe95 Thanks for the reply! Are there any other ways of printing just the even numbers?

**Comment by seanrowe95** [comment]
There are various R packages out there that you could use that would have some `is.even` ([here](https://www.rdocumentation.org/packages/schoolmath/versions/0.4/topics/is.even)) or `IsEven` ([here](https://www.rdocumentation.org/packages/Boom/versions/0.9.6/topics/is.even)) methods, but you would have to have to packages installed, and the person using your code would also have to have the packages installed to be able to use those. In the end though, those methods themselves would just use the `if (i %% 2 == 0)` logic, so you can cut out the middle man and not have to worry about those dependancies by using `if (i %% 2 == 0)`.

**Comment by n96khan** [comment]
Okay that's good to know. I'm asking because each time I try it, I get a print out of True and False statements:
> for(i in (1:10)){
+ print (i %% 2 == 0)}
[1] FALSE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE
[1] TRUE

**Comment by n96khan** [comment]
oooo I found where I was going wrong. I was mixing up my PRINT statement and my IF statement. Thanks so much!

**Comment by seanrowe95** [comment]
Great! I was just about to mention that, but I'm glad you figured that out!

**Comment by w24cai** [comment]
@n96khan You can also modify `seq()` by adding another parameter, `by = 2`. For example, if you want to print even number from 1 to 10, you can use `seq(2, 10, by=2)`.

**Comment by seanrowe95** [comment]
@w24cai this would print the the correct numbers, but it might not be what the question intends. Your for loop would just go through the numbers in the sequence (2, 4 ,6 ,etc.), whereas the question asks for your for loop to count from 1 to 10. That part of the question could just be a guide though rather than a hard rule. @brittAnderson thoughts on this?

**Comment by brittAnderson** [comment]
There are two goals to this assessment. Can you write a for loop? Can you do something "conditional" inside the for loop. Imagine that you are doing an experiment with trials 1 to 10 and every other trial you want to switch the side of the screen a picture is shown on. So you don't want to only print the right numbers, but know how to go through a series of steps and then doing something different on some of them. If your answer shows this knowledge all is good, because there will be many ways to achieve the same result.
