### ISSUE TITLE
Reopening issue- Wifi problem Xbuntu Mac

### ISSUE THREAD

**Issue by skundurt** [brittAnderson/Intro2Computing4Psychology#33]
I'm reopening this issue because I don't think a sufficient solution was found, and I'm wondering if this issue persists for other people-- currently to access Xubuntu and do any assignment, I have to restart as well as reboot twice to disable and enable the additional drivers in order for the Wifi to work... has anyone found a less time-consuming work around for this?

"@brittAnderson the on-off cycle did work, it just has to be done on every start-up

_Originally posted by @seanrowe95 in https://github.com/brittAnderson/Intro2Computing4Psychology/issues/13#issuecomment-706384234_  "

**Comment by brittAnderson** [comment]
FYI. If you find the comment that is "closed" - look in the issues page. There is a filter to only show the open issues, but you can also find the closed ones. Then when you reopen everyone will have the prior conversation available. 
I will send out an email to the class asking the mac users to pipe up.

**Comment by s296ahme** [comment]
Hi! I don’t have a Mac, but when I was first installing Xubuntu I didn’t have persistence on my USB which is why the wifi didn’t automatically connect each time. The way I “solved” it was just getting another USB and redoing all the steps carefully to get persistence so the test file and wifi connection was there in subsequent boots. It might be a hassle to get another USB and have another Xubuntu system with all your work in the previous one, but it might help solve the problem. Maybe then you could transfer all your old work to the new one. (Though I’m not fully sure how to do that part).

**Comment by seanrowe95** [comment]
I haven't been able to find a completely different work-around, but tweaking what I did before I've made it less time-consuming. Whenever you're done working with Xubuntu and are about to restart to go back to your regular Mac OS, disable the additional driver then, so when you start up Xubuntu the next time, it will already be disabled and you just have to enable it (I don't think you have to restart to enable it, at least I haven't). This removes the extra restart step, but at the cost of having to remember to disable the driver each time you're done with Xubuntu. Perhaps a script could be written to automatically disable the driver when shutting down (something I plan on looking into when I have some extra time)

**Comment by crachmad** [comment]
I also haven't been able to get a wifi persistence as well but I found out that can just disable the additional driver before shutting it down, just like @seanrowe95 did. This prevents me from having to reboot it twice.

**Comment by brittAnderson** [comment]
There is a good idea in there. If you could figure out what the actual command is that xubuntu is executing when you click and unclick that box you could use your terminal coding skills to write an alias for quitting and an additional step in starting. There is a file `~/.bashrc` that gets read and executed by your computer when it starts up. If you could figure out the equivalent terminal command was for clicking that box you could put it into your .bashrc. And if you knew the terminal command for unclicking the box you could add an *alias* to your bashrc so that you could type poweroff at the terminal and it would automatically unclick the box (metaphorically) before exiting. 

Don't spend too much time on this. You won't run an operating system from a USB for much longer, *but* the skill of editing your .bashrc and aliases are useful tools to automate repetitive computing task. 

[aliases](https://linuxize.com/post/how-to-create-bash-aliases/) 
[startup scripts](https://askubuntu.com/questions/896380/how-to-run-shell-commands-in-general-and-on-startup)
