### ISSUE TITLE
Data in Pandas - Columns

### ISSUE THREAD

**Issue by s296ahme** [brittAnderson/Intro2Computing4Psychology#37]
Hi, I’ve been able to download data from python fine, but I’ve noticed with all 3 files I got, it always says “1 column” even though I can clearly see there are more, however they are all together. It definitely doesn’t look pretty like in Dr. A’s videos. I’ve taken a picture of what it looks likes. It seems that all the columns are under 1 “main” column. I’m not too sure. This is becoming an issue because I can’t simply look at info in one column because the system doesn’t recognize “Q1” as it’s own column. 
![982856D6-C3E1-4646-80B9-5DAB64EDB0D0](https://user-images.githubusercontent.com/70985284/97785110-70a84200-1b79-11eb-81a1-7a0998ca8965.jpeg)

**Comment by bmmunds** [comment]
Hi, It looks like this data file is using backslashes to separate columns instead of commas. Maybe try a different data set and see if it still happens. Otherwise look into whether the read_csv function can handle other column separators. I used the narcissist file from psychometrics and it worked for me.

**Comment by brittAnderson** [comment]
Great job! Look at the data. That is the key. A comma separated value should be separated by "commas", but just because a file is called csv doesn't mean that it actually uses commas. And just because commas are common doesn't mean people always use them. This is tab separated. The text abbreviation for a tab is "\t" And a line return is "\n". There are several special "escaped characters" like this. But if you tell pandas the separator is actually "\t" and not "," you should get what you expect. Something like: `pandas.read_csv(filename, sep='\t')`.
