### ISSUE TITLE
Random question about the Emacs mini buffer

### ISSUE THREAD

**Issue by s296ahme** [brittAnderson/Intro2Computing4Psychology#38]
Hi, this is just a random question I’ve been wondering. In many of Dr. A’s videos, on the mini buffer on Emacs, it will say “SUBTREE (NO CHILDREN)”. I’m curious as to what this means. Thanks!

**Comment by brittAnderson** [comment]
Org mode makes everything an outline. Each level has another asterisk

* Header 1
  some text
** Header 2
    some more text. 

And so on. Header 2 is a child of header 1. When I am on subtree Header 2 (my cursor is in that block) then it says subtree no children because there is no level *** header 3,  but until you pointed it out, I never noticed that.
