### ISSUE TITLE
Errors, Errors, Everywhere - R Hangman Assessment

### ISSUE THREAD

**Issue by p2sodhi** [brittAnderson/Intro2Computing4Psychology#40]
Hi 
I'm getting an error when trying to run my code:
_Error in if (correct_ones != word_array) { : argument is of length zero_
I tried fixing this by adding in an element in the correct_ones (`correct_ones <- c('1')`) so that the length won't be 0 initially, however if I do this then my 'Win Condition' won't work. What's a better solution for this? 

Additionally, I wanted to add in 'all' or 'identical' in my 'Win Condition' so that it only executes when the two vectors are exactly equal (`if identical(correct_ones == word_array)`). But this is giving me error as well and I'm not sure why this is the case. 
![error identical](https://user-images.githubusercontent.com/71045966/98289725-9b7a0800-1f76-11eb-9447-184b2082d443.png)

Here is my code for reference: 
![hangman code R](https://user-images.githubusercontent.com/71045966/98289751-a16fe900-1f76-11eb-9a42-57103613332c.png)

**Comment by seanrowe95** [comment]
What's happening with the `correct_ones != word_array` is it's going to go through the indexes of both vectors, and evaluating whether they are not equal at each index:

```
A <- c("A", "B", "C", "D")
C <- c("A", "C", "C", "E")
> A != C

[1]  FALSE TRUE FALSE TRUE
```
That's why if you try to compare an empty vector, it throws an error

I'm assuming instead you want to check if the vectors have the same letters in them, in which case using `identical()` makes sense, except you want to pass in the two arguments to identical like this:

```
if identical(correct_ones, word_array) # checking they are equal
if !(identical(correct_ones, word_array)) # checking they are not equal
```
You can read more of the documentation for `identical()` [here](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/identical)

**Comment by p2sodhi** [comment]
I tried this (line 12 and 45) but it's still giving me syntax error when I run it. 

![error again](https://user-images.githubusercontent.com/71045966/98416014-56c0a080-204c-11eb-877d-304ad780d598.png)

**Comment by seanrowe95** [comment]
ahhhh I missed putting brackets around the if statement, my bad! Try :

```
if (identical(correct_ones, word_array)) # checking they are equal
if (!(identical(correct_ones, word_array))) # checking they are not equal
```
if there are no brackets, the code doesn't what to do with the condition

**Comment by p2sodhi** [comment]
omg this works!! Thank you! 👍
