### ISSUE TITLE
Bold_in_Rmarkdown

### ISSUE THREAD

**Issue by WisamAlkheder** [brittAnderson/Intro2Computing4Psychology#68]
Hey everyone, 
I'm not sure if anyone else is having this issue but I can't seem to make bold and italics work in R markdown. i keep getting this message:
`Error: unexpected '^' in "**"`
or
`Error: unexpected input in "_"`

Any tips?

Wisam

**Comment by anhl07** [comment]
afaik, so that error only appears if you enter the code into the console or try and run the line. R Markdown document evaluates what you type as plain text unless you put it into an r chunk. But basically, the `**bold**` should be put into the actual markdown document since that's Markdown syntax so when you knit the document, it'll be published as plain text.

**Comment by brittAnderson** [comment]
Excellent point. Look at the name on the tab where you are typing. If it says "console" or "terminal" you are writing in the R interpreter and not in a text file. Use the File menu to create a new Rmd file and write in there. Or include a code snippet here.
