### ISSUE TITLE
Xubuntu persistance - Mac

### ISSUE THREAD

**Issue by skundurt** [brittAnderson/Intro2Computing4Psychology#8]
I used UNetbootin on Mac and was able to install and open Xubuntu, but when I save a file to the desktop and restart, the file is not saved (i.e no persistence)-- has anyone found any workarounds for this on Mac?

Thanks!

**Comment by brittAnderson** [comment]
I don't have a Mac available, but when I look at this page to see what unetbootin looks like I see (second picture from the top) https://ubuntu-mate.community/t/creating-a-persistent-live-usb-using-unetbootin/20105 a "space to preserve ---something---between reboots." If defaults to zero. Did you up that number to something reasonable or the rest of the usb?

**Comment by skundurt** [comment]
Dr. Anderson, 
I changed that number to 9999Mb but there is still no persistence after that

**Comment by brittAnderson** [comment]
Hmmm. What about the USB? Had it been used for something else previously? Sometimes you can end up with multiple partitions on that USB that confuses things at boot. Even so you might still want to make sure the USB is formatted to one partition of type FAT32. This page says you can use your macs disk utility application for that: https://www.techwalla.com/articles/how-to-format-a-flash-drive-with-a-mac-to-fat32

Also, make a post on the forums on learn asking if anyone else has succeeded with netbootin and a mac. There may be another student who has made this work. They are not all following the github issues pages as closely as learn. And keep me posted.

**Comment by brittAnderson** [comment]
Another two thoughts: 
1. If you have a friend with a windows computer you could try with Rufus. The goal here is to get you a working usb linux disc AND some experience/practice with getting your hands dirty installing software and puzzling out problems. Learning how to do it on a mac specifically isn't the real issue.
2. If you can boot the non-persistent version AND you have a second slot for a USB on your computer you can make the persistent usb from Xubuntu itself using "mkusb"   After booting from the usb you would download the iso again to the usb, and also install mkusb (these will disappear on shutdown, but you don't care because you are going to use them to make a new, different usb). Then follow the instructions (but using your xubuntu 20.04 iso) from here video (https://youtu.be/ScCUDX5gtRw) or here text (https://ostechnix.com/how-to-create-persistent-live-usb-on-ubuntu/). They are the same, but just different ways of watching. 

What ever method you use, when you get it working report your experience here to help others.

**Comment by brittAnderson** [comment]
Do you have an update? If you got it working can you share your method for others who come to this thread? If not, I will go ahead and close the issue in a couple of days.

**Comment by skundurt** [comment]
Dr. Anderson, I have been able to resolve this issue using my friend's Windows laptop.
