### ISSUE TITLE
Cannot connect to internet from guest Ubuntu on the Virtual machine

### ISSUE THREAD

**Issue by a295chen** [brittAnderson/Intro2Computing4Psychology#94]
Hi, sir! I'm Angela. I failed to connect the network to Firefox in Ubuntu. May I know how do I fix it? 

![d3a29415ad469ed0ea0c426ea0e9fad](https://github.com/brittAnderson/Intro2Computing4Psychology/assets/133049127/9a06decc-085e-4628-9265-80e8269876ad)

**Comment by brittAnderson** [comment]
You will need to give some details. Are you on a mac or windows computer? Which version of OS or Windows are you running? Intel/M1/M2? What version you installed, and what you have already tried.

**Comment by brittAnderson** [comment]
In the virtual machine (the thing you installed before you installed Ubuntu) there should be a network menu somewhere. You can try changing some of those options and then shutting down and restarting. If you figure out a better one to use then make sure and post the answer here.

**Comment by a295chen** [comment]
I solved my problem by using the mobile hotspot, instead of Wi-Fi.

**Comment by a295chen** [comment]
Thank you, sir!

**Comment by brittAnderson** [comment]
I am afraid I am still a little confused. Maybe you can show me what you did in class. If you used the hotspot from your phone, and set your computer to talk to your phone then your computer did have wifi working. If you instead used your computer as a hotspot to talk to ubuntu then you still had a communication channel working. If you can give more detail here that could help a fellow student that would be nice, but if you do not have time please get my attention in class to demonstrate your solution so that I can pass it along to others.
