### ISSUE TITLE
Wrong link in the assessment plottingrandpy

### ISSUE THREAD

**Issue by Linda-Di** [brittAnderson/Intro2Computing4Psychology#98]
The wrong link is in assessments/plottingRandPyAssessment.org, in the what to submit section. It linked to assessments/~/warehouse/sdcard/gitRepos/Intro2Computing4Psychology/codeExamples/plottingExample/plottingRandPy.html. I think the correct link might be book/codeExamples/plottingExample.

**Comment by SaiTheSaint** [comment]
I think the path to the assessment is: Intro2Computing4Psychology/assessments/plottingRandPyAssessment.org
You could also access it from the dropbox by clicking on the assignment for assignment details: https://github.com/brittAnderson/Intro2Computing4Psychology/blob/master/assessments/plottingRandPyAssessment.org

**Comment by brittAnderson** [comment]
You are both right. What I did rather than linking to the older assessment file is to link the dropbox on learn to the section of the plotting material in the course notes that describes the assessment. If you find other broken links please let me know asap and I can do the same for them. After the term is over I will make a more thorough tour through the assessment links to point them all to the chapter description.
